name: Build and Deploy Flask to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: jonghun_project
  BUCKET_NAME: jonghun-cicd-bucket
  CODE_DEPLOY_APP_NAME: jonghun_cicd
  DEPLOYMENT_GROUP_NAME: jonghun_instance
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASS: ${{ secrets.MONGO_PASS }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  AWS_S3IMAGE_ACCESS_KEY_ID: ${{ secrets.AWS_S3IMAGE_ACCESS_KEY_ID}}
  AWS_S3IMAGE_SECERT_ACCESS_KEY: ${{ secrets.AWS_S3IMAGE_SECERT_ACCESS_KEY}}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER}}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME}}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" > .env
          echo "MONGO_PASS=${{ secrets.MONGO_PASS }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "AWS_S3IMAGE_ACCESS_KEY_ID=${{ secrets.AWS_S3IMAGE_ACCESS_KEY_ID }}" >> .env
          echo "AWS_S3IMAGE_SECERT_ACCESS_KEY=${{ secrets.AWS_S3IMAGE_SECERT_ACCESS_KEY }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env


      - name: Make Zip File
        run: |
          . venv/bin/activate
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip